require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExerciseGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # ExerciseGroup. As you add validations to ExerciseGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExerciseGroupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all exercise_groups as @exercise_groups" do
      exercise_group = ExerciseGroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:exercise_groups).should eq([exercise_group])
    end
  end

  describe "GET show" do
    it "assigns the requested exercise_group as @exercise_group" do
      exercise_group = ExerciseGroup.create! valid_attributes
      get :show, {:id => exercise_group.to_param}, valid_session
      assigns(:exercise_group).should eq(exercise_group)
    end
  end

  describe "GET new" do
    it "assigns a new exercise_group as @exercise_group" do
      get :new, {}, valid_session
      assigns(:exercise_group).should be_a_new(ExerciseGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested exercise_group as @exercise_group" do
      exercise_group = ExerciseGroup.create! valid_attributes
      get :edit, {:id => exercise_group.to_param}, valid_session
      assigns(:exercise_group).should eq(exercise_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExerciseGroup" do
        expect {
          post :create, {:exercise_group => valid_attributes}, valid_session
        }.to change(ExerciseGroup, :count).by(1)
      end

      it "assigns a newly created exercise_group as @exercise_group" do
        post :create, {:exercise_group => valid_attributes}, valid_session
        assigns(:exercise_group).should be_a(ExerciseGroup)
        assigns(:exercise_group).should be_persisted
      end

      it "redirects to the created exercise_group" do
        post :create, {:exercise_group => valid_attributes}, valid_session
        response.should redirect_to(ExerciseGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exercise_group as @exercise_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseGroup.any_instance.stub(:save).and_return(false)
        post :create, {:exercise_group => { "name" => "invalid value" }}, valid_session
        assigns(:exercise_group).should be_a_new(ExerciseGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseGroup.any_instance.stub(:save).and_return(false)
        post :create, {:exercise_group => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exercise_group" do
        exercise_group = ExerciseGroup.create! valid_attributes
        # Assuming there are no other exercise_groups in the database, this
        # specifies that the ExerciseGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExerciseGroup.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => exercise_group.to_param, :exercise_group => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested exercise_group as @exercise_group" do
        exercise_group = ExerciseGroup.create! valid_attributes
        put :update, {:id => exercise_group.to_param, :exercise_group => valid_attributes}, valid_session
        assigns(:exercise_group).should eq(exercise_group)
      end

      it "redirects to the exercise_group" do
        exercise_group = ExerciseGroup.create! valid_attributes
        put :update, {:id => exercise_group.to_param, :exercise_group => valid_attributes}, valid_session
        response.should redirect_to(exercise_group)
      end
    end

    describe "with invalid params" do
      it "assigns the exercise_group as @exercise_group" do
        exercise_group = ExerciseGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => exercise_group.to_param, :exercise_group => { "name" => "invalid value" }}, valid_session
        assigns(:exercise_group).should eq(exercise_group)
      end

      it "re-renders the 'edit' template" do
        exercise_group = ExerciseGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => exercise_group.to_param, :exercise_group => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exercise_group" do
      exercise_group = ExerciseGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => exercise_group.to_param}, valid_session
      }.to change(ExerciseGroup, :count).by(-1)
    end

    it "redirects to the exercise_groups list" do
      exercise_group = ExerciseGroup.create! valid_attributes
      delete :destroy, {:id => exercise_group.to_param}, valid_session
      response.should redirect_to(exercise_groups_url)
    end
  end

end
